### ISSUE TITLE
token api jne

### ISSUE THREAD

**Issue by todiadiyatmo** [kangfend/py-jne#1]
halo mas kangfend,
dapet api token jne dimana yah ?

thanks

**Comment by kangfend** [comment]
Hi Mas @todiadiyatmo,

Token JNE bisa minta langsung kepada pihak JNE atau bisa juga bongkar source code aplikasi JNE untuk Android. :smile:

**Comment by bascovon** [comment]
Ada modul nya unt virtuemart 3.X ngga bro...terima kasih

**Comment by kangfend** [comment]
@bascovon kalo untuk virtuemart saya kurang tau mas. Saya gak begitu ngerti PHP soalnya.

**Comment by lakulax** [comment]
Bro Api key sama username nya apa yah ? yg di doc gak bisa.

Terima Kasih

**Comment by kangfend** [comment]
Yang mau api_key sama usernamenya PM aja ya.
