### ISSUE TITLE
remove sensitive data

### ISSUE THREAD

**Issue by widnyana** [kangfend/py-jne#2]
pada commit `9b99d71` data memang sudah di fake, sayangnya history masih tetap ada. 

terlepas dari token tersebut masih bisa dipakai atau tidak, ada baiknya menerapkan hal [ini](https://help.github.com/articles/remove-sensitive-data/) untuk menghindari hal-hal yang tidak diinginkan di kemudian hari :)

nice works!

cheers :coffee:

**Comment by kangfend** [comment]
@widnyana terima kasih untuk koreksinya. Saya sudah menghapus history commit-nya :)
